config/routes.rb
Bdp3::Application.routes.draw do
  
  root :to => 'public#cur_issue', :as => :empty
    
  match 'issue/:issue_id' => 'public#index', :as => :public_issue, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/}
  match 'issue/:issue_id/article/:storyID' => 'public#article', :as => :public_article, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :storyID => /\d+/}
  match 'issue/:issue_id/:action' => 'public#action', :constraints => {:issue_id => /(20\d\d-[01]?\d-\d\d)/} , :as => :public_action #, fixit?:constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :action => /\w+/}
  match 'issue/archives(/yr/:mo)' => 'public#archives', :as => :public_archives, :constraints => {:yr => /\d\d/, :mo => /[01]?\d/}
 
  match 'admin/issues/:id/kill_cache' => 'issues#kill_cache', :as => 'kill_cache'
  match 'admin/issues/:id/kill_issue_cache' => 'issues#kill_issue_cache', :as => 'kill_issue_cache'
 
  scope "/admin" do
    resources :users do
      collection do
        get 'login'
        get 'logout'
        post 'do_login'
      end
    end
    resources :issues do
      member do
        get 'publish'
        get 'upload'
        post 'do_upload'
      end
      resources :articles
      resources :images
    end
  end

  match 'admin' => 'articles#new'
  
  match 'subscribe' => 'public#subscribe', :as => 'subscribe'
  match 'fund' => 'public#fund', :as => 'fund'
 
  get 'supporters/thanks', :as => :thanks_supporters
  resources :supporters
  
  match 'sitemap_index' => 'feeds#sitemap_index', :as => :sitemap_index, :defaults => {:format => 'xml'}
  match 'sitemap_old' => 'feeds#sitemap_old', :as => :sitemap_old, :defaults => {:format => 'xml'}
  match 'sitemap_news' => 'feeds#sitemap_news', :as => :sitemap_news, :defaults => {:format => 'xml'}
  match 'sitemap' => 'feeds#sitemap', :as => :sitemap, :defaults => {:format => 'xml'}
  match 'feeds/:action' => 'feeds#:action', :as => :feeds_action

  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :issue
  has_many :images

  #No article w/o an issue
  validates_presence_of :issue

  #Return 1st paragraph
  def preview
    if copy.nil?
      return ''
    end

    end_of_para = copy.index("\r\n")

    if end_of_para.nil?
      copy
    else
      copy[0..end_of_para]
    end
  end

  def in_new_section?
    section == 'New'
  end

  def in_flash_section?
    section == 'News Flash'
  end
  
  def in_updated_section?
    section == 'Updated'
  end

  def in_press_section?
    section == 'Press Release'
  end

  def self.full_feed_articles(delay)
    #debugger
    @issue = PubDate.latest
    iss = @issue.date - 7
    find(:all, :joins => 'inner join issues on articles.issue_id = issues.id',
      :conditions => ['issues.date >= ?  AND posted_at >= ?',
      iss, Time.now - delay.days], :order => 'posted_at DESC')   
  end
  
  def self.all_editorials
    iss = Date.strptime('2003-04-01', '%Y-%m-%d')
    @issue = PubDate.latest
    #debugger
    find(:all, :joins => 'inner join issues on articles.issue_id = issues.id',
      :conditions => ['issues.date > ? AND (priority = 6 OR (priority >= 85 AND priority < 90))', iss], :order => 'issues.date DESC')
  end
  
  

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  layout 'admin'

  before_filter :find_issue
  
  #All controllers are secure except the ones that are specifically marked as not secure
  def secure?
    #debugger
    true
  end

  def find_issue
    #debugger
    if params.has_key?(:issue_id)
      if params[:issue_id] =~ /20\d\d-[01]?\d-\d\d/
        @issue = Issue.find_by_strdate(params[:issue_id])
      else
        @issue = Issue.find(params[:issue_id])
      end
    else
      @issue = Issue.find(:first, :order => 'date DESC')
    end
  end

  # GET /articles
  # GET /articles.xml
  def index
    debugger
    @articles = @issue.articles.find(:all, :order => 'priority') if @issue
    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @articles.to_xml }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    debugger
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @article.to_xml }
    end
  end

  #these shouldn't be here!
  def bdp_to_html
    @article.headline.gsub!(/\s+/m, " ")
    @article.headline.gsub!(/^\s*(.*)\s*$/, '\1')
    
    @article.author.gsub!(/\s+/m, " ")
    @article.author.gsub!(/^\s*(.*)\s*$/, '\1')
    
    @article.copy.sub!(/^[ \t]*/, "<p>\t")
    @article.copy.gsub!(/\r\n[ \t]*/m, "<\/p>\r\n<p>\t")
    @article.copy.sub!(/\z/m, "<\/p>")
  end
  
  def html_to_bdp  #Fixed p vs param html bug -- also, retained span
    @article.copy.gsub!(/\&nbsp;/, " ")    #Don't see a reason for &nbsp;
    
    @article.copy.gsub!(/\&lt;/, "<")
    @article.copy.gsub!(/\&gt;/, ">")     #Editor doesn't like hand coded HTML

    @article.copy.gsub!(/\r?\n[ \t\r]*\n/m, "<\/p>") # Blank line == paragraph
    #@article.copy.gsub!(/\r?\n *\t */m, "<\/p>")     # \t with optional spaces == paragraph
    
    @article.copy.gsub!(/\r?\n/m, " ")    # Now remove all \n
    
    @article.copy.gsub!(/<p>/, " ")
    @article.copy.gsub!(/<p [^>]*?>/, " ") # Remove fancy paragraphs -- What about fancy spans?
    #@article.copy.gsub!(/<span[^>]*?>/, " ") # Remove fancy spans
    #@article.copy.gsub!(/<\/span[^>]*?>/, " ") # Remove fancy spans

    @article.copy.gsub!(/<\/p>/, "\r\n")  # </p> is true \n
    @article.copy.gsub!(/^[ \t]+/, "")    # Remove Para initial white space
    
    @article.copy.sub!(/\r\n\z/, "")      # Remove the final \n
  end


  # GET /articles/new
  def new
    #debugger
    @article = Article.new
    @article.issue = @issue
    @image = Image.new
  end

  # GET /articles/1;edit
  def edit
    #debugger
    @article = Article.find(params[:id])
    bdp_to_html()    #make the @article look more like HTML
    @image = Image.new  #When editing an article, get a new image.
  end

  # POST /articles
  # POST /articles.xml
  def create
    debugger
    @article = @issue.articles.build(params[:article])
    html_to_bdp()    #make the @article look more like the BDP standard

    params[:image] = nil if params[:image][:file_name] == ''

    unless params[:image] == nil
      fs_file_path = image_fs_path(@issue, params[:image][:file_name].original_filename())
      File.open(fs_file_path, 'wb') do |f|
        f.write(params[:image][:file_name].read)
      end
      file_name = params[:image][:file_name].original_filename()
      params[:image].delete(:file_name)
      @image = Image.new(params[:image])
      @image.file_name = file_name
    end

    @image.article = @article unless params[:image] == nil
    @article.save!
    @image.save! unless params[:image] == nil
    #debugger
    if params[:fpi] == '1'
      #MHO Add fpi here
      @issue.front_page_image = @image
      @issue.save!
    end
    flash[:notice] = 'Article was successfully created.'
    redirect_to new_issue_article_path(:issue_id => d(@issue.date))

  rescue ActiveRecord::RecordInvalid => e
    @image.valid? unless params[:image] == nil
    render :action => :new

  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    #debugger
    @article = Article.find(params[:id])

    params[:image] = nil if params[:image][:file_name] == nil #''

    unless params[:image] == nil
      fs_file_path = image_fs_path(@issue, params[:image][:file_name].original_filename())
      File.open(fs_file_path, 'wb') do |f|
        f.write(params[:image][:file_name].read)
      end
      file_name = params[:image][:file_name].original_filename()
      params[:image].delete(:file_name)
      @image = Image.new(params[:image])
      @image.file_name = file_name
    end

    Article.transaction do
      @image.article = @article unless params[:image] == nil
      if @article.update_attributes(params[:article])
        html_to_bdp()    #make the @article look more like the BDP standard
        @article.save!
        flash[:notice] = 'Article was successfully updated.'
      end
      @image.save! unless params[:image] == nil
      #debugger
      if params[:fpi] == '1'
        #MHO Add fpi here
        @issue.front_page_image = @image
        @issue.save!
      end
      redirect_to new_issue_article_path(:issue_id => d(@issue.date))
    end

  rescue ActiveRecord::RecordInvalid => e
    @image.valid? unless params[:image] == nil
    render :action => :edit
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    #debugger
    @article = Article.find(params[:id])
    @issue = @article.issue
    @article.destroy

    respond_to do |format|
      format.html { redirect_to new_issue_article_path(:issue_id => d(@issue.date)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_left_menu
    render(:partial => 'menu')
  end

  def articles_right_menu
    render(:partial => 'r_menu')
  end
end

app/views/articles/_form.html.haml
//- debugger
%p#notice= notice
= form_for [@issue, @article], :html => {multipart: true} do |f|
  %p
    .left
      %b
        Date/Time
      = f.datetime_select :posted_at
    .focus.right
      = f.submit @submit_title #'Create or Update this Article'
    .right
      %b
        Label
      = select('article', 'section', [['Updated'], ['New'], ['News Flash'], ['Press Release']], {:selected => @article.section, :include_blank => true})


  %p.clear
    %b
      Priority
    - if @article.priority.nil?
      /= f.text_field(:priority, :value => next_article_priority, :size => 3)
      = f.text_field(:priority, :value => -200, :size => 3)
      /= f.text_field(:priority, :size => 3)
    - else
      = f.text_field(:priority, :size => 3)
    %span{:style => 'font-sizexx: 10pt'}
      \-200- Ignored, -0 Extra, 1+ Page One, 6 Editorial, 7+ Features, 20+ Election Section, 25+ Press Rels., 30+ Columns, 
      40+ Letters, 45+ Commentary,
      %br
      50+ Arts Lists, 55+ Arts, 60+ Home Columnists, 66+ Home Features,
      /%br
      70+ Events Lists, 75+ Events, 80+ Ed Cartoon, 85+ Ed Back Fence, 90+ Obits, 200+ Ignored
  %p
    .left
      %b
        Headline
      %br/
      = f.text_area(:headline, :cols => 70, :rows => 2)
    .right
      %b
        Author
      %br/
      = f.text_area(:author, :cols => 40, :rows => 2)
  %p
    %table{:style => 'font-sizexx: 10pt'}
      %tr
        %td By Becky O'Malley
        /%td By Riya Bhattacharjee
        /%td By Raymond Barglow
        /%td By Richard Brenneman
        /%tr
        /%td By Justin DeFreitas,
        /%td By J. Douglas Allen-Taylor
        /%td By Daniella Thompson
        %td By Bay City News
        /%td By Matt Cantor
      %tr
        %td By Ron Sullivan
        %td By Conn Hallinan
        /%tr
        %td{:colspan => 1}By X, Special to The Planet
        %td{:colspan => 1}By Ken Bullock, Special to The Planet
        %td By Steven Finacom
  %p
    %b
      Copy
    %br/
    = f.text_area(:copy, :cols => 120, :rows => 30)
    %table{:style => 'font-sizxxe: 10pt'}
      %tr
        %td{:colspan => 1}
          \&lt;a href="http://URL" target="_blank"> text &lt;/a>
        %td
          \&lt;blockquote> text &lt;/blockquote>
        %td
          \&lt;i> text &lt;/i>
        %td
          \&lt;b> text &lt;/b>
        %td
          \&lt;u> text &lt;/u>
      %tr
        %td
          \&lt;a href="http://URL" > text &lt;/a>
        %td{:colspan => 1}
          \&lt;a href="mailto:X@Y" > text &lt;/a>
        %td
          \&lt;br />&lt;br />
        %td
          \&lt;sup>X&lt;/sup>
        %td
          \&lt;sub>X&lt;/sub>
      %tr
        %td{:colspan => 2}
          \&lt;iframe src="http://URL" width="100%" frameborder="1" height="900" >&lt;/iframe>
        %td{:colspan => 4}
          \&lt;img src="/photos/issue/XX.jpg" class="free_img"/>
      %tr
        %td   
          \&lt;a href="/pdfs/XX.pdf" > text &lt;/a>
      %tr
        %td{:colspan => 5}
          \&lt;hr />&lt;b>Comments? Write to &lt;a href="mailto:opinion@berkeleydailyplanet.com">opinion at berkeleydailyplanet.com&lt;/a>.  
          If you sign your real name to your comment we'll publish it.&lt;/b> Please include a phone number (not for publication) so that we can verify authorship.
  
  %br/
  .focus.right
    = f.submit @submit_title #'Create or Update this Article'
  %fieldset
    %legend
      Add an image to this article
    // = fixit error_messages_for :image
    = fields_for :image do |i|
      %table
        %tr
          %td
            %label{:for => "image_file_name"}
              File Name:
          %td
            = i.file_field(:file_name, :size => 80)
        %tr
          %td
            %label{:for => "image_author"}
              Author:
          %td
            = i.text_area(:author, :cols => 50, :rows => 1)
        %tr
          %td
            %label{:for => "image_caption"}
              Caption:
          %td
            = i.text_area(:caption, :cols => 90, :rows => 4)
  %br/
  %p.focus.left
    %span.red{:style => 'font-size: 16px'}
      Check box if this image should also be made the Front Page Image
    = check_box_tag('fpi')
  %br/
  %br/




app/views/articles/_menu.html.haml
%h1
  Issue Date
  %br/
  = @issue.date.to_s
%br/
%p.menu
  = link_to( 'Remove the Cache for this Issue', kill_issue_cache_path(:id => d(@issue.date))) unless @issue.new_record?
%br/
%p.menu
  = link_to( 'Preview this Issue', public_issue_path(:issue_id => d(@issue.date))) unless @issue.new_record? 
%br/
%p.menu
  = link_to( 'View the Main Site', empty_path )
%br/
%p.menu
  = link_to( 'Add or Update an Article', new_issue_article_path(:issue_id => d(@issue.date))) unless @issue.new_record? 
%br/
%br/
\*****
%br/
%p.menu
  = link_to( 'Choose a Different Issue', issues_path()) if session['user_name'] == 'mho' 
%br/
%p.menu
  = admin_prev_issue_link
%br/
%p.menu
  = admin_next_issue_link
%br/
%p.menu
  = link_to( 'Upload Files', upload_issue_path(:id => d(@issue.date))) unless @issue.new_record? 
%br/
\*****
%br/
%p.menu
  = link_to( 'Make a Stand-alone Front Page Image', new_issue_image_path(:issue_id => d(@issue.date))) unless @issue.new_record? 
%br/
%p.menu
  = link_to( 'Remove All Caches for All Issues', kill_cache_path(:id => d(@issue.date))) unless @issue.new_record? 
%br/
%br/
\*****
%br/
%p.menu
  = link_to( 'Create a New Issue', new_issue_path, :confirm => 'Are you sure?  Creating an issue has side effects.' )
%br/
%p.menu
  = link_to( 'Publish the "latest" Issue', publish_issue_path(:id => d(@issue.date)), :confirm => 'Are you sure?  Publishing an issue has side effects.' ) unless @issue.new_record?
%br/
%br/
\*****
%br/
%p.menu
  = link_to('Edit/Add Users', users_path) if session['user_name'] == 'mho'
%br/
%p.menu
  = link_to('Delete the Current Issue!!', issue_path(:id => d(@issue.date)), :confirm => 'Are you sure?  Deleteing an issue may have side effects.', :method => :delete) unless @issue.new_record? || session['user_name'] != 'mho'
%br/
%p.menu
  = link_to( 'Logout', logout_users_path )
%br/ 
\*****

app/views/articles/_r_menu.html.haml
- if image = @issue.front_page_image
  %h1
    Front Page Image: 
  = link_to image.file_name, edit_issue_image_path(:id => image.id, :issue_id => d(@issue.date))
%h1
  Articles:
%br/
- @articles = @issue.articles.find(:all, :order => 'priority') if @issue
- for article in @articles
  %span.red
    = article.priority
  = article.headline
  %i
    = article.author
  = article.section
  %br/
  %table
    %tr
      %td
        = article.id
      %td
        //- debugger
        = link_to 'Edit', edit_issue_article_path(:id => article, :issue_id => d(article.issue.date))
      %td
        = link_to 'Preview', public_article_path(:issue_id => d(article.issue.date), :storyID => article)
      %td
        = link_to 'Delete', issue_article_path(:id => article, :issue_id => d(article.issue.date)), :confirm => 'Are you sure?', :method => :delete
  Photos:
  - @images = article.images
  - for image in @images
    = link_to image.file_name, edit_issue_image_path(:id => image.id, :issue_id => d(@issue.date)) if image
  %hr{:size => 1}/

app/views/articles/edit.html.haml
%h1
  Modify this article.
//- debugger
- @submit_title ='Modify this Article'

= render 'form'
%br/
%br/
%p
  Current Images:
= article_photos(@article)

app/views/articles/index.html.haml
%p#notice= notice

%h1
  Listing articles
%table
  %tr
    %th
      Issue
    %th
      Author
    %th
      Headline
    /%th
    /  Copy
    %th
      Section
    %th
      Priority
  - for article in @articles
    %tr
      %td
        = h article.issue_id
      %td
        = h article.author
      %td
        = h article.headline
      /%td
      /  = h article.copy
      %td
        = h article.section
      %td
        = h article.priority
      %td
        = link_to 'Show', issue_article_path(:id => article)
      %td
        = link_to 'Edit', edit_issue_article_path(:id => article)
      %td
        = link_to 'Destroy', issue_article_path(:id => article), :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New article', new_issue_article_path

app/views/articles/new.html.haml
//- debugger
%h1
  Add a new article for issue:
  = d(@issue.date)
  
  - @submit_title ='Create this Article'

= render 'form'

app/views/articles/show.html.haml
%p#notice= notice
%p
  %b
    Issue:
  = h @article.issue_id
%p
  %b
    Author:
  = h @article.author
%p
  %b
    Headline:
  = raw @article.headline
%p
  %b
    Copy:
  //= raw @article.copy
  = article_photos(@article) 
  .copy
    <p>
    = raw @article.copy.gsub(/\r?\n/, "&nbsp;</p><p>")
    </p>
%p
  %b
    Section:
  = h @article.section
%p
  %b
    Priority:
  = h @article.priority
= link_to 'Edit', edit_issue_article_path(:id => @article)
|
= link_to 'Back', issue_articles_path