config/routes.rb
Bdp3::Application.routes.draw do
  
  root :to => 'public#cur_issue', :as => :empty
    
  match 'issue/:issue_id' => 'public#index', :as => :public_issue, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/}
  match 'issue/:issue_id/article/:storyID' => 'public#article', :as => :public_article, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :storyID => /\d+/}
  match 'issue/:issue_id/:action' => 'public#action', :constraints => {:issue_id => /(20\d\d-[01]?\d-\d\d)/} , :as => :public_action #, fixit?:constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :action => /\w+/}
  match 'issue/archives(/yr/:mo)' => 'public#archives', :as => :public_archives, :constraints => {:yr => /\d\d/, :mo => /[01]?\d/}
 
  match 'admin/issues/:id/kill_cache' => 'issues#kill_cache', :as => 'kill_cache'
  match 'admin/issues/:id/kill_issue_cache' => 'issues#kill_issue_cache', :as => 'kill_issue_cache'
 
  scope "/admin" do
    resources :users do
      collection do
        get 'login'
        get 'logout'
        post 'do_login'
      end
    end
    resources :issues do
      member do
        get 'publish'
        get 'upload'
        post 'do_upload'
      end
      resources :articles
      resources :images
    end
  end

  match 'admin' => 'articles#new'
  
  match 'subscribe' => 'public#subscribe', :as => 'subscribe'
  match 'fund' => 'public#fund', :as => 'fund'
 
  get 'supporters/thanks', :as => :thanks_supporters
  resources :supporters
  
  match 'sitemap_index' => 'feeds#sitemap_index', :as => :sitemap_index, :defaults => {:format => 'xml'}
  match 'sitemap_old' => 'feeds#sitemap_old', :as => :sitemap_old, :defaults => {:format => 'xml'}
  match 'sitemap_news' => 'feeds#sitemap_news', :as => :sitemap_news, :defaults => {:format => 'xml'}
  match 'sitemap' => 'feeds#sitemap', :as => :sitemap, :defaults => {:format => 'xml'}
  match 'feeds/:action' => 'feeds#:action', :as => :feeds_action

  
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base

  def authenticate(user_name, entered_password)
    hashed_entered_password = Digest::SHA1.hexdigest(entered_password)
    if hashed_entered_password == hashed_password
      true
    else
      false
    end
  end

  def password
    ''
  end

  def password=(value)
    write_attribute('hashed_password', Digest::SHA1.hexdigest(value))
  end

  def self.random_pronouncable_password(size = 4)
    c = %w(b c d f g h j k l m n p qu r s t v w x z ch cr fr nd ng nk nt ph pr rd sh sl sp st th tr)
    v = %w(a e i o u y)
    f, r = true, ''
    (size * 2).times do
      r << (f ? c[rand * c.size] : v[rand * v.size])
      f = !f
    end
    r
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'admin'

  def secure?
    #debugger
    if (action_name == 'login')
      false
    else
      true
    end
  end
  hide_action :secure?

  # GET /admin/users
  # GET /admin/users.xml
  def index
    #debugger
    @users = User.find(:all)

    respond_to do |format|
      format.html # index.rhtml
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  #MHOdef show
  #  @user = User.find(params[:id])
  #  respond_to do |format|
  #    format.html # show.rhtml
  #    format.xml  { render :xml => @user.to_xml }
  #  end
  #end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit #MHO REady for Rails 2
  def edit
    @user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.xml
  def create
    #debugger
    if params[:user][:password].strip != params[:confirm_password].strip
      @user = User.new(params[:user])
      respond_to do |format|
        flash[:error] = "The passwords do not match"
        format.html { render :action => 'edit' }
      end
    else
      @user = User.new(params[:user])
      respond_to do |format|
        if @user.save
          flash[:notice] = 'User was successfully created.'
          format.html { redirect_to users_path }
        else
          flash[:notice] = 'Problem with creating User.'
          format.html { render :action => "new" }
        end
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml
  def update
    #debugger
    if params[:user][:password].strip != params[:confirm_password].strip
      @user = User.find(params[:id])
      respond_to do |format|
        flash[:error] = "The passwords do not match"
        format.html { render :action => 'edit' }
      end
    else
      @user = User.find(params[:id])
      respond_to do |format|
        if @user.update_attributes(params[:user])
          flash[:notice] = 'User was successfully updated.'
          format.html { redirect_to users_path }
        else
          flash[:notice] = 'Problem with updating User.'
          format.html { render :action => "edit" }
        end
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User deleted.'

    respond_to do |format|
      format.html { redirect_to users_path }
    end
  end

  def logout
    #debugger
    session['user_name'] = nil
    redirect_to(login_users_path)
  end

  def login
    #debugger
    session['user_name'] = nil
  end

  def do_login
    #debugger
    redirect_to(admin_path)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def users_left_menu
    render(:partial => 'menu')
  end
end

app/views/users/_form.html.haml
%p#notice= notice
= form_for(@user) do |f|
  %table
    %tr
      %td
        = f.label :user_name
      %td
        = f.text_field :user_name
    %tr
      %td
        = f.label :password
      %td
        = f.password_field :password
    %tr
      %td
        %label{"for"=>"confirm_password"}
          Confirm Password
      %td
        %input#confirm_password{"name"=>"confirm_password", "size"=>"30", "type"=>"password"}/
  
  = submit_tag @submit_type

app/views/users/_menu.html.haml
%h1
  User Menu
%p.menu
  = link_to('Add or Edit an Issue', admin_path) if session['user_name'] # == 'mho' #any session?
%p.menu
  = link_to 'Logout', logout_users_path if session['user_name'] != nil
%p.menu
  = link_to('View the Main Site', empty_path)

app/views/users/edit.html.haml
%h1
  Edit user's name and password for
  = @user.user_name

- @submit_type = "Update"

= render 'form'

= link_to 'List All Users', users_path

app/views/users/index.html.haml
%h1
  List of Users
%p

%table
  %tr
    %th
      User Name:
    %th
      User Id:
  - for user in @users
    %tr
      %td
        = h user.user_name
      %td
        = h user.id
      %td
        = link_to 'Edit', edit_user_path(user)
      %td
        = link_to 'Delete', user_path(user), :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New user', new_user_path

app/views/users/login.html.haml
%h1
  Login:
= form_for(:user, url: {action: :do_login}) do |f|
  %table
    %tr
      %td
        = f.label :user_name
        = f.text_field :user_name
    %tr
      %td
        = f.label :password
        = f.password_field(:password, size: 20) 
    %tr
      %td
        = f.submit :login


app/views/users/new.html.haml
%h1
  New user

- @submit_type = "Create"

= render 'form'

= link_to 'List All Users', users_path