config/routes.rb
Bdp3::Application.routes.draw do
  
  root :to => 'public#cur_issue', :as => :empty
    
  match 'issue/:issue_id' => 'public#index', :as => :public_issue, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/}
  match 'issue/:issue_id/article/:storyID' => 'public#article', :as => :public_article, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :storyID => /\d+/}
  match 'issue/:issue_id/:action' => 'public#action', :constraints => {:issue_id => /(20\d\d-[01]?\d-\d\d)/} , :as => :public_action #, fixit?:constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :action => /\w+/}
  match 'issue/archives(/yr/:mo)' => 'public#archives', :as => :public_archives, :constraints => {:yr => /\d\d/, :mo => /[01]?\d/}
 
  match 'admin/issues/:id/kill_cache' => 'issues#kill_cache', :as => 'kill_cache'
  match 'admin/issues/:id/kill_issue_cache' => 'issues#kill_issue_cache', :as => 'kill_issue_cache'
 
  scope "/admin" do
    resources :users do
      collection do
        get 'login'
        get 'logout'
        post 'do_login'
      end
    end
    resources :issues do
      member do
        get 'publish'
        get 'upload'
        post 'do_upload'
      end
      resources :articles
      resources :images
    end
  end

  match 'admin' => 'articles#new'
  
  match 'subscribe' => 'public#subscribe', :as => 'subscribe'
  match 'fund' => 'public#fund', :as => 'fund'
 
  get 'supporters/thanks', :as => :thanks_supporters
  resources :supporters
  
  match 'sitemap_index' => 'feeds#sitemap_index', :as => :sitemap_index, :defaults => {:format => 'xml'}
  match 'sitemap_old' => 'feeds#sitemap_old', :as => :sitemap_old, :defaults => {:format => 'xml'}
  match 'sitemap_news' => 'feeds#sitemap_news', :as => :sitemap_news, :defaults => {:format => 'xml'}
  match 'sitemap' => 'feeds#sitemap', :as => :sitemap, :defaults => {:format => 'xml'}
  match 'feeds/:action' => 'feeds#:action', :as => :feeds_action

  
end

app/models/supporter.rb
class Supporter < ActiveRecord::Base
  CONTACT_METHODS = \
  {
    1 => 'email',
    2 => 'phone',
    3 => 'U.S. mail',
  }
  def self.contact_methods_options_for_select
    CONTACT_METHODS.to_a.collect { |c| [c[1], c[0]] }
  end
end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  
  #All controllers are secure except the ones that are specifically marked as not secure
  def secure?
    #debugger
    true
  end

  # GET /supporter
  # GET /supporter.xml
  def index
    @supporters = Supporter.paginate(:all, :page => params[:page], :order => 'last_name') #find(:all)
    @issue = PubDate.latest

    respond_to do |format|
      format.html { render :layout => 'public' } # index.html.erb
      format.xml  { render :xml => @supporter }
    end
  end

  # GET /supporter/1
  # GET /supporter/1.xml
  def show
    @supporter = Supporter.find(params[:id])
    @issue = PubDate.latest

    respond_to do |format|
      format.html { render :layout => 'public' } # show.html.erb
      format.xml  { render :xml => @supporter }
    end
  end

  # GET /supporter/new
  # GET /supporter/new.xml
  def new
    @supporter = Supporter.new
    @issue = PubDate.latest

    respond_to do |format|
      format.html { render :layout => 'public' } # new.html.erb
      format.xml  { render :xml => @supporter }
    end
  end

  def thanks
    @issue = PubDate.latest
    render :layout => 'public'
  end

  # GET /supporter/1/edit
  def edit
    @supporter = Supporter.find(params[:id])
    @issue = PubDate.latest
    render :layout => 'public'
  end

  # POST /supporter
  # POST /supporter.xml
  def create
    @supporter = Supporter.new(params[:supporter])
    respond_to do |format|
      if @supporter.save
        flash[:notice] = 'Supporter was successfully created.'
        if user.nil?
          format.html { redirect_to(:action => 'thanks') }
        else 
          format.html { redirect_to(:action => 'index') } 
        end
        format.xml  { render :xml => @supporter, :status => :created, :location => @supporter }
      else
        flash[:notice] = 'Creation Error.'
        format.html { render :action => "new" }
        format.xml  { render :xml => @supporter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /supporter/1
  # PUT /supporter/1.xml
  def update
    @supporter = Supporter.find(params[:id])
    respond_to do |format|
      if @supporter.update_attributes(params[:supporter])
        flash[:notice] = 'Supporter was successfully updated.'
        format.html { redirect_to(:action => 'index') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @supporter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /supporter/1
  # DELETE /supporter/1.xml
  def destroy
    @supporter = Supporter.find(params[:id])
    @supporter.destroy

    respond_to do |format|
      format.html { redirect_to(:action => 'index') }
      format.xml  { head :ok }
    end
  end

protected
  def secure?
    if ['create', 'new', 'thanks'].include?(action_name)
      false
    else
      true
    end
  end
end

app/helpers/supporters_helper.rb
module SupportersHelper
end

app/views/supporters/_form.html.haml
%table
  %tr
    %td
      = f.label_for(:first_name)
    %td
      = f.text_field(:first_name)
  %tr
    %td
      = f.label_for(:last_name)
    %td
      = f.text_field(:last_name)
  %tr
    %td
      = f.label_for(:street)
    %td
      = f.text_field(:street_address, :size => 50)
  %tr
    %td
      = f.label_for(:city)
    %td
      = f.text_field(:city)
  %tr
    %td
      = f.label_for(:state)
    %td
      = f.select(:state,  State.options_for_select)
  %tr
    %td
      = f.label_for(:zip)
    %td
      = f.text_field(:zipcode, :size => 12)
  %tr
    %td
      = f.label_for(:phone)
    %td
      = f.text_field(:phone, :size => 15)
  %tr
    %td
      = f.label_for(:email)
    %td
      = f.text_field(:email, :size => 50)
  %tr
    %td
      = f.label_for(:preferred_contact_method_id)
    %td
      = f.select(:preferred_contact_method_id, Supporter.contact_methods_options_for_select)
  %tr
    %td
      = f.label_for(:notes)
    %td
      = f.text_area(:notes, :cols => 50, :rows => 5)

app/views/supporters/edit.html.haml
#content
  .gutter
    %h1.large_air_below
      Edit the Supporter's Information
    = "ID: #{@supporter.id}, Name: #{@supporter.first_name}  #{@supporter.last_name}"
    %br/
    %br/
    %p#notice= notice
    
    - form_for(@supporter, :html => { :method => :put }) do |f|
      %p
        = render(:partial => 'form')
      %p
        = submit_tag "Update"
    
    %br/
    %br/
    = link_to 'List All Supporters', supporters_path

app/views/supporters/index.html.haml
#content
  .gutter
    %p#notice= notice
    %h1.large_air_below
      List all Supporters
    %table
      - for supporter in @supporters
        %tr
          %td
            = "#{h supporter.id}: &nbsp; "
          %td
            = "#{h supporter.first_name} "
          %td
            = "#{h supporter.last_name}, &nbsp; "
          %td
            = "#{h supporter.phone}, &nbsp; "
          %td
            = "#{h supporter.email} &nbsp; "
          %td
            = link_to 'Show &nbsp; ', supporter_path(supporter)
          %td
            = link_to 'Edit &nbsp; ', edit_supporter_path(supporter), :confirm => 'Are you sure?'
          %td
            = link_to 'Delete &nbsp; ', supporter_path(supporter), :confirm => 'Are you sure?  Deleteing a supporter is permanent!', :method => :delete
    %br/
    %h3
      Select a different page of Supporters
    = will_paginate @supporters
    %br/
    = link_to 'Add a new supporter', new_supporter_path

app/views/supporters/new.html.haml
- @title = "Become a Friend of The Planet"
#content
  .gutter
    %h1.large_air_below
      I'd like to sign up as a "Friend of The Planet".
    - form_for(@supporter) do |f|
      %p
        = render(:partial => 'form')
      %p
        = submit_tag "submit"
= partial_include("public/nav_topics")

app/views/supporters/show.html.haml
#content
  .gutter
    %h1.large_air_below
      View the Supporter's Information
    = "ID: #{@supporter.id}, Name: #{@supporter.first_name}  #{@supporter.last_name}"
    %br/
    %br/
    %p#notice= notice

    = form_for(@supporter) do |f|
      %p
        = render(:partial => 'form')
    
    %br/
    %br/
    = link_to 'List All Supporters', supporters_path

app/views/supporters/thanks.html.haml
- @title = "Thanks!"
#content
  .gutter
    %p#notice= notice
    %h1.large_air_below
      Thanks for becoming a Friend of The Planet!
    %p
      If you have not yet donated to the Fund for Local Reporting, you may do so
      = link_to 'here.', fund_path
    %br
    %p
      Otherwise, you may return to the current issue
      = link_to 'here.', empty_path

= partial_include("public/nav_topics")