config/routes.rb
Bdp3::Application.routes.draw do
  
  root :to => 'public#cur_issue', :as => :empty
    
  match 'issue/:issue_id' => 'public#index', :as => :public_issue, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/}
  match 'issue/:issue_id/article/:storyID' => 'public#article', :as => :public_article, :constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :storyID => /\d+/}
  match 'issue/:issue_id/:action' => 'public#action', :constraints => {:issue_id => /(20\d\d-[01]?\d-\d\d)/} , :as => :public_action #, fixit?:constraints => {:issue_id => /latest|(20\d\d-[01]?\d-\d\d)/, :action => /\w+/}
  match 'issue/archives(/yr/:mo)' => 'public#archives', :as => :public_archives, :constraints => {:yr => /\d\d/, :mo => /[01]?\d/}
 
  match 'admin/issues/:id/kill_cache' => 'issues#kill_cache', :as => 'kill_cache'
  match 'admin/issues/:id/kill_issue_cache' => 'issues#kill_issue_cache', :as => 'kill_issue_cache'
 
  scope "/admin" do
    resources :users do
      collection do
        get 'login'
        get 'logout'
        post 'do_login'
      end
    end
    resources :issues do
      member do
        get 'publish'
        get 'upload'
        post 'do_upload'
      end
      resources :articles
      resources :images
    end
  end

  match 'admin' => 'articles#new'
  
  match 'subscribe' => 'public#subscribe', :as => 'subscribe'
  match 'fund' => 'public#fund', :as => 'fund'
 
  get 'supporters/thanks', :as => :thanks_supporters
  resources :supporters
  
  match 'sitemap_index' => 'feeds#sitemap_index', :as => :sitemap_index, :defaults => {:format => 'xml'}
  match 'sitemap_old' => 'feeds#sitemap_old', :as => :sitemap_old, :defaults => {:format => 'xml'}
  match 'sitemap_news' => 'feeds#sitemap_news', :as => :sitemap_news, :defaults => {:format => 'xml'}
  match 'sitemap' => 'feeds#sitemap', :as => :sitemap, :defaults => {:format => 'xml'}
  match 'feeds/:action' => 'feeds#:action', :as => :feeds_action

  
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  has_one :front_page_issue, :class_name => 'Issue', :foreign_key => 'front_page_image'

  def issue
    if article != nil
      article.issue
    else
      front_page_issue
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  layout 'admin'

  before_filter :find_issue
  
  #All controllers are secure except the ones that are specifically marked as not secure
  def secure?
    #debugger
    true
  end

  def find_issue
    #debugger
    if params.has_key?(:issue_id)
      if params[:issue_id] == 'latest'
        @issue = Issue.find(:first, :order => 'date DESC')
        params[:issue_id] = d(@issue.date)
      else
        @issue = Issue.find_by_strdate(params[:issue_id])
      end
    # old why? fixit? else
    #  @issue = Issue.find(:first, :order => 'date DESC')
    end
    #@articles = @issue.articles.find(:all, :order => 'priority')
  end

  # GET /images
  # GET /images.xml
  #MHO index only for articles
  def xx_index #MHO Work on this
    #debugger
    if params.has_key?(:article_id) #not @article.nil?
      @article = Article.find(params[:article_id])
      @images = @article.images
    else
      @image = @issue.front_page_image
    end
    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @images.to_xml }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  #MHO Following actions are polymorphic between issue and article!
  def show
    #debugger
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @image.to_xml }
    end
  end

  # GET /images/new
  def new
    #debugger
    @image = Image.new
    #if params.has_key?(:article_id)
    #  @article = Article.find(params[:article_id]) #MHO Never happens
    #  @image.article = @article
    #end
  end

  # GET /images/1;edit
  def edit
    #debugger
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    #debugger
    #MHO check for blank file_name
    params[:image] = nil if params[:image][:file_name] == ''

    unless params[:image] == nil
      fs_file_path = image_fs_path(@issue, params[:image][:file_name].original_filename())
      File.open(fs_file_path, 'wb') do |f|
        f.write(params[:image][:file_name].read)
      end
      file_name = params[:image][:file_name].original_filename()
      params[:image].delete(:file_name)
      @image = Image.new(params[:image])
      @image.file_name = file_name

      #unless @article.nil?
      #  @image.article = @article #MHO Never happens
      #end

    respond_to do |format|
      #debugger
      if @image.save
        #if @article.nil?
        @issue.front_page_image = @image #MHO Always happens
        @issue.save!
        #end
        format.html { redirect_to new_issue_article_path(:issue_id => d(@issue.date)) }
        flash[:notice] = 'Image was successfully created.'
        format.xml  { head :created, :location => image_path(@image) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors.to_xml }
      end
    end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    #debugger
    @image = Image.find(params[:id])
    #MHO Ever not fpi?
    if params[:fpi] == '1'
      #MHO Add fpi here
      @issue.front_page_image = @image
      @issue.save!
    end

    respond_to do |format|
      if @image.update_attributes(params[:image])
        flash[:notice] = 'Image was successfully updated.'
        format.html { redirect_to new_issue_article_path(:issue_id => d(@issue.date)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors.to_xml }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    #debugger
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html {redirect_to new_issue_article_path(:issue_id => d(@issue.date))}
      format.xml  { head :ok }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  
  def images_left_menu
    if @image.nil?
      ''
    else
      render(:partial => 'menu')
    end
  end

  def images_right_menu
    render(:partial => 'r_menu')
  end

end

app/views/images/_menu.html.haml
.menu_title
  Image: 
  = @image.id
Issue: 
%br/
= link_to(d(@issue.date), new_issue_article_path(:issue_id => d(@issue.date)))
%br/
%br/
= link_to 'Remove the Cache for this Issue', kill_issue_cache_path(:id => d(@issue.date)) unless @issue.new_record?
%br/
%br/
%br/
= link_to('delete', issue_image_path(:id => @image.id, :issue_id => d(@image.issue.date)), :method => :delete, :confirm => 'Are you sure you want to delete this image? This action cannot be undone.') unless @image.new_record?

app/views/images/_r_menu.html.haml
%h1
  Photo Files for Date:
  %br/
  = @issue.date
%br/
%table
  - if all_photo_files(@issue)
    - for file in all_photo_files(@issue)
      - debugger
      %tr
        %td
          = file
      %tr
        %td
          = show_photo_file(@issue, file, :width => '100px')
  


app/views/images/edit.html.haml
%h1
  Edit this Image
  %p#notice= notice
= form_for(:image, :url => issue_image_path(:id => @image.id), :html => { :method => :put }) do |f|
  %br/
  %p
    %b
      Article
    %br/
    = f.text_field :article_id
  %br/
  %p
    %b
      File Name
    %br/
    = f.text_field :file_name, :size => 80
  - unless @issue.front_page_image.nil?
    %br/
    %p
      %b
        Front Page Image File Name:
      %br/
      = @issue.front_page_image.file_name
  %br/
  %p
    %b
      Author
    %br/
    = f.text_area(:author, :cols => 50, :rows => 1)
  %br/
  %p
    %b
      Caption
    %br/
    = f.text_area(:caption, :cols => 90, :rows => 4)
  %p
    %span.red
      Should this image also be made the Front Page Image?
    = check_box_tag('fpi')
    %br/
    %br/
    = submit_tag 'Update'

%br/
%br/
= photo_img(@image)

app/views/images/index.html.haml
%p#notice= notice
- if @article.nil?
  %h1
    Listing Front Page Image for Issue:
    = h d(@issue.date)
  %table
    %tr
      %th
        ID
      %th
        File name
      %th
        Author
      %th
        Caption
    %tr
      %td
        = h @image.id 
        \&nbsp;
      %td
        = h @image.file_name
      %td
        = h @image.author
      %td
        = h @image.caption
      %td
        = link_to 'Show', issue_image_path(:id => @image.id, :issue_id => d(@issue.date))
      %td
        = link_to 'Edit', edit_issue_image_path(:id => @image.id, :issue_id => d(@issue.date))
      %td
        = link_to 'Destroy', issue_image_path(:id => @image.id, :issue_id => d(@issue.date)), :confirm => 'Are you sure?', :method => :delete
  %br/
  = link_to 'New Front Page Image', new_issue_image_path
  
-else #MHO Currently, we can't get here
  %h1
    Listing images for article:
    = h @article.id
  %table
    %tr
      %th
        ID
      %th
        File name
      %th
        Author
      %th
        Caption
    - for image in @images
      %tr
        %td
          = h image.id 
          \&nbsp;
        %td
          = h image.file_name
        %td
          = h image.author
        %td
          = h image.caption
        %td
          = link_to 'Show', issue_article_image_path(:id => image.id, :article_id => @article.id, :issue_id => d(@issue.date))
        %td
          = link_to 'Edit', edit_issue_article_image_path(:id => image.id, :article_id => @article.id, :issue_id => d(@issue.date))
        %td
          = link_to 'Destroy', issue_article_image_path(:id => image.id, :article_id => @article.id, :issue_id => d(@issue.date)), :confirm => 'Are you sure?', :method => :delete
  %br/
  /= link_to 'New image', new_issue_article_image_path

app/views/images/new.html.haml
%p#notice= notice

%h1
  New Stand-Alone Front Page Image
= form_for(:image, :url => issue_images_path(:issue_id => d(@issue.date)), :html => {:enctype => "multipart/form-data"}) do |f|
  %table
    %tr
      %td
        %label{:for => "image_file_name"}
          File Name:
      %td
        = f.file_field(:file_name, :size => 80)
    %tr
      %td
        %label{:for => "image_author"}
          Author:
      %td
        = f.text_area(:author, :cols => 50, :rows => 1)
    %tr
      %td
        %label{:for => "image_caption"}
          Caption:
      %td
        = f.text_area(:caption, :cols => 90, :rows => 4)
  %p
    = submit_tag "Create Image"
      
- unless @issue.front_page_image.nil?
  %br/
  %br/
  %h1
    Current Front Page Image:
  = @issue.front_page_image.file_name
  %br/
  = front_page_photo

app/views/images/show.html.haml
%p#notice= notice
%p
  %b
    Article:
  = h @image.article_id
%p
  %b
    File name:
  = h @image.file_name
%p
  %b
    Author:
  = h @image.author
%p
  %b
    Caption:
  = h @image.caption
= link_to 'Edit', edit_issue_image_path(:id => @image.id, :issue_id => d(@issue.date))
|
= link_to 'Back', issue_images_path
%br/
%br/
= photo_img(@image)